# reference variables
source = None
geometry = None
rotation = None
nRows = None
nCols = None
rowSize = None
colSize = None
max_modes = 5

# export variables
ref_shoreline = None
model = None
observed = None
shoreline_lons = None
shoreline_lats = None
S = None
r = None
var_ratio = None
wave_var = None